name: Greeter

on: 
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        default: world

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
